version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build helloworld.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - helloworld
